spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: qfjava
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.67.84:3306/db_love_travel?serverTimezone=UTC&characterEncoding=UTF8

mybatis-plus:
  mapper-locations: classpath*:/com/qfedu/love_travel/mapper/*Mapper.xml
  type-aliases-package: com.qfedu.love_travel.entity



server:
  port: 8080





