spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: duanjiliang
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_1901?serverTimezone=UTC&characterEncoding=UTF8
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
server:
  port: 8080
